2019/04/10 16:15:02 [crit] 19197#19197: *934 connect() to unix:/home/ledinhtri/ldt_dat_thesis/DataAnnotationTool/run/uwsgi.sock failed (2: No such file or directory) while connecting to upstream, client: 172.28.182.4, server: 172.28.10.144, request: "GET /gvlab-dat/workspace/ HTTP/1.1", upstream: "uwsgi://unix:/home/ledinhtri/ldt_dat_thesis/DataAnnotationTool/run/uwsgi.sock:", host: "172.28.10.144:8080", referrer: "http://172.28.10.144:8080/gvlab-dat/datuser/login/"
2019/04/10 16:15:03 [crit] 19197#19197: *934 connect() to unix:/home/ledinhtri/ldt_dat_thesis/DataAnnotationTool/run/uwsgi.sock failed (2: No such file or directory) while connecting to upstream, client: 172.28.182.4, server: 172.28.10.144, request: "GET /gvlab-dat/workspace/ HTTP/1.1", upstream: "uwsgi://unix:/home/ledinhtri/ldt_dat_thesis/DataAnnotationTool/run/uwsgi.sock:", host: "172.28.10.144:8080", referrer: "http://172.28.10.144:8080/gvlab-dat/datuser/login/"
