
2019/07/24 14:14:00 [crit] 1976#1976: *30114 connect() to unix:/home/ledinhtri/ledinhtri/DataAnnotationTool/run/uwsgi.sock failed (2: No such file or directory) while connecting to upstream, client: 172.28.183.160, server: 172.28.182.130, request: "GET /gvlab-dat/workspace/next/70951/ HTTP/1.1", upstream: "uwsgi://unix:/home/ledinhtri/ledinhtri/DataAnnotationTool/run/uwsgi.sock:", host: "172.28.183.160", referrer: "https://172.28.183.160:10001/gvlab-dat/workspace/ws-65/"
2019/07/26 15:40:55 [error] 1972#1972: *41113 upstream prematurely closed connection while reading response header from upstream, client: 172.28.183.160, server: 172.28.182.130, request: "GET /gvlab-dat/workspace/settings/api-get-data/ HTTP/1.1", upstream: "uwsgi://unix:/home/ledinhtri/ledinhtri/DataAnnotationTool/run/uwsgi.sock:", host: "172.28.183.160", referrer: "https://172.28.183.160:10001/gvlab-dat/workspace/ws-65/"
2019/07/26 15:42:19 [crit] 1983#1983: *41195 connect() to unix:/home/ledinhtri/ledinhtri/DataAnnotationTool/run/uwsgi.sock failed (2: No such file or directory) while connecting to upstream, client: 172.28.183.160, server: 172.28.182.130, request: "GET /gvlab-dat/workspace/outworkspace/-1 HTTP/1.1", upstream: "uwsgi://unix:/home/ledinhtri/ledinhtri/DataAnnotationTool/run/uwsgi.sock:", host: "172.28.183.160", referrer: "https://172.28.183.160:10001/gvlab-dat/workspace/ws-64/"
